### ISSUE TITLE
Doors lead to many things

### ISSUE THREAD

**Issue by IntelligencePending** [LilyC-Dev/warband_mod_source#9]
Including money. Sometimes doors will give you gold, sometimes they take it away. Most of the time it gets put in your bank account. A guy on the forum says it leads to Narnia.

Haven't gotten around to looking in to this yet but making a note. This is just all too absurd.

**Comment by LilyC-Dev** [comment]
I honestly haven't ever seen a working door in Warband before, and don't know of any in the mod, do you know where they actually are? Also because it's effecting the banking system we could try commenting that out. I wanted to replace it with the banking system from Floris (money lenders and land owners I think is the name https://web.archive.org/web/20150905152310/http://mbmodwiki.ollclan.eu:80/Bank) but was having some trouble adding that before due to it just not compiling.

**Comment by IntelligencePending** [comment]
I don't think the door issue isn't related directly to the banking system, but the moneylender code looks pretty doable from a quick glance so at some point I think it would be good to switch.

**Comment by LilyC-Dev** [comment]
Yay! 😄 

Also, the bug is probably related to the wider problems with prisons / castles from the reports on the forums.

**Comment by IntelligencePending** [comment]
D-oh. Figured it out. Doors in scenes go by menu item number. That's why they go to seemingly random places, their numbers got offset by new menus.

Not too long left for this issue now.
